### ISSUE TITLE
Flask main loop vs glib main loop of pydbus

### ISSUE THREAD

**Issue by exsypher** [LEW21/pydbus#24]
Hi,
I am thinking of using your pydbus to establish a rpc connection to a c++ program. At the same time I am using a Flask program whose main loop may interfere with the glib main loop. How can I make this work, or am I wrong here? Hope someone can help me, if this is even the right place to ask for that... (if not, i am sry)

Greetings
eX

**Comment by LEW21** [comment]
In past, I was trying to integrate glib's and gevent's event loop, and unfortunately I've failed. I guess I should try again.

I think that the best way would be to run glib's event loop and everything glib-related in another thread, and use event queues to synchronize it.

**Comment by exsypher** [comment]
Alright thanks for the tipp, i will try to do that. =)

**Comment by LEW21** [comment]
This week I'll release version with support for gevent's event loop - so it'll work with all gevent-based webservers (like gunicorn -k gevent).

**Comment by exsypher** [comment]
If I can replace the threading with the gevent loop somehow that would be pretty cool of course!

**Comment by LEW21** [comment]
Works for most cases, looks like I didn't test signals. Fixed in https://github.com/LEW21/pydbus/commit/05ee9e946f991eab74ca2e13a74716ee2c2c5974.

I didn't merge it yet because I'm thinking about integrating greenglib with [pgi](https://github.com/lazka/pgi) in some way, but I guess that would be a long term project, and I should just release the code I have.

(Note that I'm not sure if I'm going to merge the Python 2 unicode patch.)

BTW, I don't think the Client.run() loop is necessary, I think gevent is able to handle external (pydbus-sent) events while the control is in serve_forever().

**Comment by exsypher** [comment]
I've tested it, everything works so far now. The Client.run() loop was in fact not necessary. Thanks!
I'll close the issue now and reopen it when I find any bugs.

Greetings

**Comment by exsypher** [comment]
I hoped you would include the greenlib stuff in the next release but you didn't. Is there a reason why?

**Comment by LEW21** [comment]
I've wanted to release 0.6 with stable features only, and I want to work on greenlib a bit more. I hope to return to it this month.

**Comment by vilhalmer** [comment]
Any chance this branch can be brought back to life? I was able to rebase it on top of master and run the tests without too much trouble.

Edit: looks like there's a bit of async cleanup to be done for python 3.7, and some gevent api changes.
